openapi: "3.1.0"
info:
  title: "artifacts API"
  description: "artifacts API"
  version: "1.0.0"
servers:
  - url: "https://artifacts"
paths:
  /artifacts-service/artifact:
    get:
      description: ""
      parameters:
        - name: "type"
          in: "query"
          required: false
          schema:
            type: "string"
        - name: "commit"
          in: "query"
          required: false
          schema:
            type: "string"
        - name: "branch"
          in: "query"
          required: false
          schema:
            type: "string"
        - name: "platform"
          in: "query"
          required: false
          schema:
            type: "string"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "[platform] type wasn't resolved"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "object"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
            text/plain:
              schema:
                type: "string"
                format: "byte"
  /artifacts-service/upload:
    post:
      description: ""
      parameters:
        - name: "auth_token"
          in: "query"
          required: false
          schema:
            type: "string"
        - name: "type"
          in: "query"
          required: false
          schema:
            type: "string"
        - name: "platform"
          in: "query"
          required: false
          schema:
            type: "string"
        - name: "commit"
          in: "query"
          required: false
          schema:
            type: "string"
        - name: "branch"
          in: "query"
          required: false
          schema:
            type: "string"
      requestBody:
        content:
          '*/*':
            schema:
              type: "array"
              items:
                type: "string"
                format: "byte"
        required: true
      responses:
        "401":
          description: "Unauthorized"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "[auth_token] is invalid"
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "content is empty"
                Example#2:
                  value: "[type] is invalid"
                Example#3:
                  value: "[platform] type wasn't resolved"
                Example#4:
                  value: "one of query parameters is null"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"