name: Jar file builder

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  auth_token: someRandomToken0DontUseInProdPls010101

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 20
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Create example config
        run: |
          sudo mkdir /etc/game-server/
          sudo chmod -R ugo+rws /etc/artifacts-server/
          touch /etc/artifacts-server/config.yaml
          echo -n ${{ secrets.TEST_CONFIG }} | base64 -d  >> /etc/artifacts-server/config.yaml
      - name: Run tests
        run: gradle test
      - name: Build jar
        run: gradle build
      - name: Upload jar file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: build/libs/artifacts-all.jar
